sudo: required
dist: trusty
language: generic

install:
  # Travis CI does not make the home directory world readable by default,
  # which prevents Apache from reading the server source.
  - sudo chmod 755 /home/travis/
  - ./setup/setup.sh

script:
  # Test server, client, and frontend
  - ./test.sh
  # Verify that docs build
  - ./tools/build_docs.sh
  # Check formatting
  - ./tools/format.sh --all
  # Verify Vagrant setup.
  - sudo apt-get -y install vagrant
  - (cd setup && vagrant up && vagrant -f destroy)
