sudo: false
dist: xenial
language: generic

services:
  - docker

install:
  # Setup tools.
  - sudo ./tools/setup_tools.sh
  # Build the images.
  - ./server/interop-server.sh build
  - ./client/interop-client.sh build

script:
  # Test server.
  - ./server/interop-server.sh create_db
  - ./server/interop-server.sh test
  # Test client.
  - ./server/interop-server.sh load_test_data
  - ./server/interop-server.sh up_d
  - ./client/interop-client.sh test
  - ./server/interop-server.sh down
  # Check formatting.
  - ./tools/format.sh --all
